// File generated from our OpenAPI spec by Stainless.

package ai.hanzo.api.models.team

import ai.hanzo.api.core.JsonValue
import ai.hanzo.api.core.jsonMapper
import ai.hanzo.api.models.organization.BudgetTable
import ai.hanzo.api.models.organization.OrganizationMembershipTable
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TeamAddMemberResponseTest {

    @Test
    fun create() {
        val teamAddMemberResponse =
            TeamAddMemberResponse.builder()
                .teamId("team_id")
                .addUpdatedTeamMembership(
                    TeamAddMemberResponse.UpdatedTeamMembership.builder()
                        .litellmBudgetTable(
                            BudgetTable.builder()
                                .budgetDuration("budget_duration")
                                .budgetId("budget_id")
                                .maxBudget(0.0)
                                .maxParallelRequests(0L)
                                .modelMaxBudget(
                                    BudgetTable.ModelMaxBudget.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .rpmLimit(0L)
                                .softBudget(0.0)
                                .tpmLimit(0L)
                                .build()
                        )
                        .teamId("team_id")
                        .userId("user_id")
                        .budgetId("budget_id")
                        .spend(0.0)
                        .build()
                )
                .addUpdatedUser(
                    TeamAddMemberResponse.UpdatedUser.builder()
                        .userId("user_id")
                        .budgetDuration("budget_duration")
                        .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .maxBudget(0.0)
                        .metadata(
                            TeamAddMemberResponse.UpdatedUser.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelMaxBudget(
                            TeamAddMemberResponse.UpdatedUser.ModelMaxBudget.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelSpend(
                            TeamAddMemberResponse.UpdatedUser.ModelSpend.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .addModel(JsonValue.from(mapOf<String, Any>()))
                        .objectPermission(
                            TeamAddMemberResponse.UpdatedUser.ObjectPermission.builder()
                                .objectPermissionId("object_permission_id")
                                .addAgentAccessGroup("string")
                                .addAgent("string")
                                .addMcpAccessGroup("string")
                                .addMcpServer("string")
                                .mcpToolPermissions(
                                    TeamAddMemberResponse.UpdatedUser.ObjectPermission
                                        .McpToolPermissions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(listOf("string")),
                                        )
                                        .build()
                                )
                                .addVectorStore("string")
                                .build()
                        )
                        .addOrganizationMembership(
                            OrganizationMembershipTable.builder()
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .organizationId("organization_id")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .userId("user_id")
                                .budgetId("budget_id")
                                .litellmBudgetTable(
                                    BudgetTable.builder()
                                        .budgetDuration("budget_duration")
                                        .budgetId("budget_id")
                                        .maxBudget(0.0)
                                        .maxParallelRequests(0L)
                                        .modelMaxBudget(
                                            BudgetTable.ModelMaxBudget.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .rpmLimit(0L)
                                        .softBudget(0.0)
                                        .tpmLimit(0L)
                                        .build()
                                )
                                .spend(0.0)
                                .user(JsonValue.from(mapOf<String, Any>()))
                                .userRole("user_role")
                                .build()
                        )
                        .rpmLimit(0L)
                        .spend(0.0)
                        .ssoUserId("sso_user_id")
                        .addTeam("string")
                        .tpmLimit(0L)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .userAlias("user_alias")
                        .userEmail("user_email")
                        .userRole("user_role")
                        .build()
                )
                .addAdmin(JsonValue.from(mapOf<String, Any>()))
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .litellmModelTable(
                    TeamAddMemberResponse.LitellmModelTable.builder()
                        .createdBy("created_by")
                        .updatedBy("updated_by")
                        .id(0L)
                        .modelAliases(
                            TeamAddMemberResponse.LitellmModelTable.ModelAliases.UnionMember0
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .team(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .addMember(JsonValue.from(mapOf<String, Any>()))
                .addMembersWithRole(
                    Member.builder()
                        .role(Member.Role.ADMIN)
                        .userEmail("user_email")
                        .userId("user_id")
                        .build()
                )
                .metadata(
                    TeamAddMemberResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelId(0L)
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    TeamAddMemberResponse.ObjectPermission.builder()
                        .objectPermissionId("object_permission_id")
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            TeamAddMemberResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .objectPermissionId("object_permission_id")
                .organizationId("organization_id")
                .routerSettings(
                    TeamAddMemberResponse.RouterSettings.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .rpmLimit(0L)
                .spend(0.0)
                .teamAlias("team_alias")
                .addTeamMemberPermission("string")
                .tpmLimit(0L)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        assertThat(teamAddMemberResponse.teamId()).isEqualTo("team_id")
        assertThat(teamAddMemberResponse.updatedTeamMemberships())
            .containsExactly(
                TeamAddMemberResponse.UpdatedTeamMembership.builder()
                    .litellmBudgetTable(
                        BudgetTable.builder()
                            .budgetDuration("budget_duration")
                            .budgetId("budget_id")
                            .maxBudget(0.0)
                            .maxParallelRequests(0L)
                            .modelMaxBudget(
                                BudgetTable.ModelMaxBudget.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .rpmLimit(0L)
                            .softBudget(0.0)
                            .tpmLimit(0L)
                            .build()
                    )
                    .teamId("team_id")
                    .userId("user_id")
                    .budgetId("budget_id")
                    .spend(0.0)
                    .build()
            )
        assertThat(teamAddMemberResponse.updatedUsers())
            .containsExactly(
                TeamAddMemberResponse.UpdatedUser.builder()
                    .userId("user_id")
                    .budgetDuration("budget_duration")
                    .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .maxBudget(0.0)
                    .metadata(
                        TeamAddMemberResponse.UpdatedUser.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .modelMaxBudget(
                        TeamAddMemberResponse.UpdatedUser.ModelMaxBudget.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .modelSpend(
                        TeamAddMemberResponse.UpdatedUser.ModelSpend.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .addModel(JsonValue.from(mapOf<String, Any>()))
                    .objectPermission(
                        TeamAddMemberResponse.UpdatedUser.ObjectPermission.builder()
                            .objectPermissionId("object_permission_id")
                            .addAgentAccessGroup("string")
                            .addAgent("string")
                            .addMcpAccessGroup("string")
                            .addMcpServer("string")
                            .mcpToolPermissions(
                                TeamAddMemberResponse.UpdatedUser.ObjectPermission
                                    .McpToolPermissions
                                    .builder()
                                    .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                    .build()
                            )
                            .addVectorStore("string")
                            .build()
                    )
                    .addOrganizationMembership(
                        OrganizationMembershipTable.builder()
                            .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .organizationId("organization_id")
                            .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                            .userId("user_id")
                            .budgetId("budget_id")
                            .litellmBudgetTable(
                                BudgetTable.builder()
                                    .budgetDuration("budget_duration")
                                    .budgetId("budget_id")
                                    .maxBudget(0.0)
                                    .maxParallelRequests(0L)
                                    .modelMaxBudget(
                                        BudgetTable.ModelMaxBudget.builder()
                                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                                            .build()
                                    )
                                    .rpmLimit(0L)
                                    .softBudget(0.0)
                                    .tpmLimit(0L)
                                    .build()
                            )
                            .spend(0.0)
                            .user(JsonValue.from(mapOf<String, Any>()))
                            .userRole("user_role")
                            .build()
                    )
                    .rpmLimit(0L)
                    .spend(0.0)
                    .ssoUserId("sso_user_id")
                    .addTeam("string")
                    .tpmLimit(0L)
                    .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .userAlias("user_alias")
                    .userEmail("user_email")
                    .userRole("user_role")
                    .build()
            )
        assertThat(teamAddMemberResponse.admins().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(teamAddMemberResponse.blocked()).contains(true)
        assertThat(teamAddMemberResponse.budgetDuration()).contains("budget_duration")
        assertThat(teamAddMemberResponse.budgetResetAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(teamAddMemberResponse.createdAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(teamAddMemberResponse.litellmModelTable())
            .contains(
                TeamAddMemberResponse.LitellmModelTable.builder()
                    .createdBy("created_by")
                    .updatedBy("updated_by")
                    .id(0L)
                    .modelAliases(
                        TeamAddMemberResponse.LitellmModelTable.ModelAliases.UnionMember0.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .team(JsonValue.from(mapOf<String, Any>()))
                    .build()
            )
        assertThat(teamAddMemberResponse.maxBudget()).contains(0.0)
        assertThat(teamAddMemberResponse.maxParallelRequests()).contains(0L)
        assertThat(teamAddMemberResponse.members().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(teamAddMemberResponse.membersWithRoles().getOrNull())
            .containsExactly(
                Member.builder()
                    .role(Member.Role.ADMIN)
                    .userEmail("user_email")
                    .userId("user_id")
                    .build()
            )
        assertThat(teamAddMemberResponse.metadata())
            .contains(
                TeamAddMemberResponse.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(teamAddMemberResponse.modelId()).contains(0L)
        assertThat(teamAddMemberResponse.models().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(teamAddMemberResponse.objectPermission())
            .contains(
                TeamAddMemberResponse.ObjectPermission.builder()
                    .objectPermissionId("object_permission_id")
                    .addAgentAccessGroup("string")
                    .addAgent("string")
                    .addMcpAccessGroup("string")
                    .addMcpServer("string")
                    .mcpToolPermissions(
                        TeamAddMemberResponse.ObjectPermission.McpToolPermissions.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .addVectorStore("string")
                    .build()
            )
        assertThat(teamAddMemberResponse.objectPermissionId()).contains("object_permission_id")
        assertThat(teamAddMemberResponse.organizationId()).contains("organization_id")
        assertThat(teamAddMemberResponse.routerSettings())
            .contains(
                TeamAddMemberResponse.RouterSettings.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(teamAddMemberResponse.rpmLimit()).contains(0L)
        assertThat(teamAddMemberResponse.spend()).contains(0.0)
        assertThat(teamAddMemberResponse.teamAlias()).contains("team_alias")
        assertThat(teamAddMemberResponse.teamMemberPermissions().getOrNull())
            .containsExactly("string")
        assertThat(teamAddMemberResponse.tpmLimit()).contains(0L)
        assertThat(teamAddMemberResponse.updatedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val teamAddMemberResponse =
            TeamAddMemberResponse.builder()
                .teamId("team_id")
                .addUpdatedTeamMembership(
                    TeamAddMemberResponse.UpdatedTeamMembership.builder()
                        .litellmBudgetTable(
                            BudgetTable.builder()
                                .budgetDuration("budget_duration")
                                .budgetId("budget_id")
                                .maxBudget(0.0)
                                .maxParallelRequests(0L)
                                .modelMaxBudget(
                                    BudgetTable.ModelMaxBudget.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .rpmLimit(0L)
                                .softBudget(0.0)
                                .tpmLimit(0L)
                                .build()
                        )
                        .teamId("team_id")
                        .userId("user_id")
                        .budgetId("budget_id")
                        .spend(0.0)
                        .build()
                )
                .addUpdatedUser(
                    TeamAddMemberResponse.UpdatedUser.builder()
                        .userId("user_id")
                        .budgetDuration("budget_duration")
                        .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .maxBudget(0.0)
                        .metadata(
                            TeamAddMemberResponse.UpdatedUser.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelMaxBudget(
                            TeamAddMemberResponse.UpdatedUser.ModelMaxBudget.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .modelSpend(
                            TeamAddMemberResponse.UpdatedUser.ModelSpend.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .addModel(JsonValue.from(mapOf<String, Any>()))
                        .objectPermission(
                            TeamAddMemberResponse.UpdatedUser.ObjectPermission.builder()
                                .objectPermissionId("object_permission_id")
                                .addAgentAccessGroup("string")
                                .addAgent("string")
                                .addMcpAccessGroup("string")
                                .addMcpServer("string")
                                .mcpToolPermissions(
                                    TeamAddMemberResponse.UpdatedUser.ObjectPermission
                                        .McpToolPermissions
                                        .builder()
                                        .putAdditionalProperty(
                                            "foo",
                                            JsonValue.from(listOf("string")),
                                        )
                                        .build()
                                )
                                .addVectorStore("string")
                                .build()
                        )
                        .addOrganizationMembership(
                            OrganizationMembershipTable.builder()
                                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .organizationId("organization_id")
                                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                                .userId("user_id")
                                .budgetId("budget_id")
                                .litellmBudgetTable(
                                    BudgetTable.builder()
                                        .budgetDuration("budget_duration")
                                        .budgetId("budget_id")
                                        .maxBudget(0.0)
                                        .maxParallelRequests(0L)
                                        .modelMaxBudget(
                                            BudgetTable.ModelMaxBudget.builder()
                                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                                .build()
                                        )
                                        .rpmLimit(0L)
                                        .softBudget(0.0)
                                        .tpmLimit(0L)
                                        .build()
                                )
                                .spend(0.0)
                                .user(JsonValue.from(mapOf<String, Any>()))
                                .userRole("user_role")
                                .build()
                        )
                        .rpmLimit(0L)
                        .spend(0.0)
                        .ssoUserId("sso_user_id")
                        .addTeam("string")
                        .tpmLimit(0L)
                        .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                        .userAlias("user_alias")
                        .userEmail("user_email")
                        .userRole("user_role")
                        .build()
                )
                .addAdmin(JsonValue.from(mapOf<String, Any>()))
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetResetAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .litellmModelTable(
                    TeamAddMemberResponse.LitellmModelTable.builder()
                        .createdBy("created_by")
                        .updatedBy("updated_by")
                        .id(0L)
                        .modelAliases(
                            TeamAddMemberResponse.LitellmModelTable.ModelAliases.UnionMember0
                                .builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .team(JsonValue.from(mapOf<String, Any>()))
                        .build()
                )
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .addMember(JsonValue.from(mapOf<String, Any>()))
                .addMembersWithRole(
                    Member.builder()
                        .role(Member.Role.ADMIN)
                        .userEmail("user_email")
                        .userId("user_id")
                        .build()
                )
                .metadata(
                    TeamAddMemberResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelId(0L)
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    TeamAddMemberResponse.ObjectPermission.builder()
                        .objectPermissionId("object_permission_id")
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            TeamAddMemberResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .objectPermissionId("object_permission_id")
                .organizationId("organization_id")
                .routerSettings(
                    TeamAddMemberResponse.RouterSettings.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .rpmLimit(0L)
                .spend(0.0)
                .teamAlias("team_alias")
                .addTeamMemberPermission("string")
                .tpmLimit(0L)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .build()

        val roundtrippedTeamAddMemberResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(teamAddMemberResponse),
                jacksonTypeRef<TeamAddMemberResponse>(),
            )

        assertThat(roundtrippedTeamAddMemberResponse).isEqualTo(teamAddMemberResponse)
    }
}
