// File generated from our OpenAPI spec by Stainless.

package com.hanzo_ai.api.models.user

import com.hanzo_ai.api.core.JsonValue
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class UserCreateResponseTest {

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun create() {
        val userCreateResponse =
            UserCreateResponse.builder()
                .expires(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .key("key")
                .token("token")
                .aliases(JsonValue.from(mapOf<String, Any>()))
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetId("budget_id")
                .config(JsonValue.from(mapOf<String, Any>()))
                .createdBy("created_by")
                .duration("duration")
                .addEnforcedParam("string")
                .addGuardrail("string")
                .keyAlias("key_alias")
                .keyName("key_name")
                .llmBudgetTable(JsonValue.from(mapOf<String, Any>()))
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(JsonValue.from(mapOf<String, Any>()))
                .modelMaxBudget(JsonValue.from(mapOf<String, Any>()))
                .modelRpmLimit(JsonValue.from(mapOf<String, Any>()))
                .modelTpmLimit(JsonValue.from(mapOf<String, Any>()))
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .permissions(JsonValue.from(mapOf<String, Any>()))
                .rpmLimit(0L)
                .spend(0.0)
                .addTag("string")
                .teamId("team_id")
                .addTeam(JsonValue.from(mapOf<String, Any>()))
                .tokenId("token_id")
                .tpmLimit(0L)
                .updatedBy("updated_by")
                .userAlias("user_alias")
                .userEmail("user_email")
                .userId("user_id")
                .userRole(UserCreateResponse.UserRole.PROXY_ADMIN)
                .build()

        assertThat(userCreateResponse.expires())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(userCreateResponse.key()).isEqualTo("key")
        assertThat(userCreateResponse.token()).contains("token")
        assertThat(userCreateResponse._aliases()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.allowedCacheControls().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.blocked()).contains(true)
        assertThat(userCreateResponse.budgetDuration()).contains("budget_duration")
        assertThat(userCreateResponse.budgetId()).contains("budget_id")
        assertThat(userCreateResponse._config()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.createdBy()).contains("created_by")
        assertThat(userCreateResponse.duration()).contains("duration")
        assertThat(userCreateResponse.enforcedParams().getOrNull()).containsExactly("string")
        assertThat(userCreateResponse.guardrails().getOrNull()).containsExactly("string")
        assertThat(userCreateResponse.keyAlias()).contains("key_alias")
        assertThat(userCreateResponse.keyName()).contains("key_name")
        assertThat(userCreateResponse._llmBudgetTable())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.maxBudget()).contains(0.0)
        assertThat(userCreateResponse.maxParallelRequests()).contains(0L)
        assertThat(userCreateResponse._metadata()).isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse._modelMaxBudget())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse._modelRpmLimit())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse._modelTpmLimit())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.models().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse._permissions())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.rpmLimit()).contains(0L)
        assertThat(userCreateResponse.spend()).contains(0.0)
        assertThat(userCreateResponse.tags().getOrNull()).containsExactly("string")
        assertThat(userCreateResponse.teamId()).contains("team_id")
        assertThat(userCreateResponse.teams().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.tokenId()).contains("token_id")
        assertThat(userCreateResponse.tpmLimit()).contains(0L)
        assertThat(userCreateResponse.updatedBy()).contains("updated_by")
        assertThat(userCreateResponse.userAlias()).contains("user_alias")
        assertThat(userCreateResponse.userEmail()).contains("user_email")
        assertThat(userCreateResponse.userId()).contains("user_id")
        assertThat(userCreateResponse.userRole()).contains(UserCreateResponse.UserRole.PROXY_ADMIN)
    }
}
