// File generated from our OpenAPI spec by Stainless.

package ai.hanzo.api.models.user

import ai.hanzo.api.core.JsonValue
import ai.hanzo.api.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class UserCreateResponseTest {

    @Test
    fun create() {
        val userCreateResponse =
            UserCreateResponse.builder()
                .key("key")
                .token("token")
                .aliases(
                    UserCreateResponse.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedPassthroughRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedVectorStoreIndex(
                    UserCreateResponse.AllowedVectorStoreIndex.builder()
                        .indexName("index_name")
                        .addIndexPermission(
                            UserCreateResponse.AllowedVectorStoreIndex.IndexPermission.READ
                        )
                        .build()
                )
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetId("budget_id")
                .config(
                    UserCreateResponse.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .duration("duration")
                .addEnforcedParam("string")
                .expires(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addGuardrail("string")
                .keyAlias("key_alias")
                .keyName("key_name")
                .litellmBudgetTable(JsonValue.from(mapOf<String, Any>()))
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    UserCreateResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    UserCreateResponse.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelRpmLimit(
                    UserCreateResponse.ModelRpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelTpmLimit(
                    UserCreateResponse.ModelTpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    UserCreateResponse.ObjectPermission.builder()
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            UserCreateResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .organizationId("organization_id")
                .permissions(
                    UserCreateResponse.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addPrompt("string")
                .routerSettings(
                    UserCreateResponse.RouterSettings.builder()
                        .allowedFails(0L)
                        .addContextWindowFallback(
                            UserCreateResponse.RouterSettings.ContextWindowFallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .cooldownTime(0.0)
                        .addFallback(
                            UserCreateResponse.RouterSettings.Fallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .maxRetries(0L)
                        .modelGroupAlias(
                            UserCreateResponse.RouterSettings.ModelGroupAlias.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .modelGroupRetryPolicy(
                            UserCreateResponse.RouterSettings.ModelGroupRetryPolicy.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .numRetries(0L)
                        .retryAfter(0.0)
                        .routingStrategy("routing_strategy")
                        .routingStrategyArgs(
                            UserCreateResponse.RouterSettings.RoutingStrategyArgs.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .timeout(0.0)
                        .build()
                )
                .rpmLimit(0L)
                .rpmLimitType(UserCreateResponse.RpmLimitType.GUARANTEED_THROUGHPUT)
                .spend(0.0)
                .addTag("string")
                .teamId("team_id")
                .addTeam(JsonValue.from(mapOf<String, Any>()))
                .tokenId("token_id")
                .tpmLimit(0L)
                .tpmLimitType(UserCreateResponse.TpmLimitType.GUARANTEED_THROUGHPUT)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .userAlias("user_alias")
                .userEmail("user_email")
                .userId("user_id")
                .userRole(UserCreateResponse.UserRole.PROXY_ADMIN)
                .build()

        assertThat(userCreateResponse.key()).isEqualTo("key")
        assertThat(userCreateResponse.token()).contains("token")
        assertThat(userCreateResponse.aliases())
            .contains(
                UserCreateResponse.Aliases.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userCreateResponse.allowedCacheControls().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.allowedPassthroughRoutes().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.allowedRoutes().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.allowedVectorStoreIndexes().getOrNull())
            .containsExactly(
                UserCreateResponse.AllowedVectorStoreIndex.builder()
                    .indexName("index_name")
                    .addIndexPermission(
                        UserCreateResponse.AllowedVectorStoreIndex.IndexPermission.READ
                    )
                    .build()
            )
        assertThat(userCreateResponse.blocked()).contains(true)
        assertThat(userCreateResponse.budgetDuration()).contains("budget_duration")
        assertThat(userCreateResponse.budgetId()).contains("budget_id")
        assertThat(userCreateResponse.config())
            .contains(
                UserCreateResponse.Config.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userCreateResponse.createdAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(userCreateResponse.createdBy()).contains("created_by")
        assertThat(userCreateResponse.duration()).contains("duration")
        assertThat(userCreateResponse.enforcedParams().getOrNull()).containsExactly("string")
        assertThat(userCreateResponse.expires())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(userCreateResponse.guardrails().getOrNull()).containsExactly("string")
        assertThat(userCreateResponse.keyAlias()).contains("key_alias")
        assertThat(userCreateResponse.keyName()).contains("key_name")
        assertThat(userCreateResponse._litellmBudgetTable())
            .isEqualTo(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.maxBudget()).contains(0.0)
        assertThat(userCreateResponse.maxParallelRequests()).contains(0L)
        assertThat(userCreateResponse.metadata())
            .contains(
                UserCreateResponse.Metadata.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userCreateResponse.modelMaxBudget())
            .contains(
                UserCreateResponse.ModelMaxBudget.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userCreateResponse.modelRpmLimit())
            .contains(
                UserCreateResponse.ModelRpmLimit.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userCreateResponse.modelTpmLimit())
            .contains(
                UserCreateResponse.ModelTpmLimit.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userCreateResponse.models().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.objectPermission())
            .contains(
                UserCreateResponse.ObjectPermission.builder()
                    .addAgentAccessGroup("string")
                    .addAgent("string")
                    .addMcpAccessGroup("string")
                    .addMcpServer("string")
                    .mcpToolPermissions(
                        UserCreateResponse.ObjectPermission.McpToolPermissions.builder()
                            .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                            .build()
                    )
                    .addVectorStore("string")
                    .build()
            )
        assertThat(userCreateResponse.organizationId()).contains("organization_id")
        assertThat(userCreateResponse.permissions())
            .contains(
                UserCreateResponse.Permissions.builder()
                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                    .build()
            )
        assertThat(userCreateResponse.prompts().getOrNull()).containsExactly("string")
        assertThat(userCreateResponse.routerSettings())
            .contains(
                UserCreateResponse.RouterSettings.builder()
                    .allowedFails(0L)
                    .addContextWindowFallback(
                        UserCreateResponse.RouterSettings.ContextWindowFallback.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .cooldownTime(0.0)
                    .addFallback(
                        UserCreateResponse.RouterSettings.Fallback.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .maxRetries(0L)
                    .modelGroupAlias(
                        UserCreateResponse.RouterSettings.ModelGroupAlias.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .modelGroupRetryPolicy(
                        UserCreateResponse.RouterSettings.ModelGroupRetryPolicy.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .numRetries(0L)
                    .retryAfter(0.0)
                    .routingStrategy("routing_strategy")
                    .routingStrategyArgs(
                        UserCreateResponse.RouterSettings.RoutingStrategyArgs.builder()
                            .putAdditionalProperty("foo", JsonValue.from("bar"))
                            .build()
                    )
                    .timeout(0.0)
                    .build()
            )
        assertThat(userCreateResponse.rpmLimit()).contains(0L)
        assertThat(userCreateResponse.rpmLimitType())
            .contains(UserCreateResponse.RpmLimitType.GUARANTEED_THROUGHPUT)
        assertThat(userCreateResponse.spend()).contains(0.0)
        assertThat(userCreateResponse.tags().getOrNull()).containsExactly("string")
        assertThat(userCreateResponse.teamId()).contains("team_id")
        assertThat(userCreateResponse.teams().getOrNull())
            .containsExactly(JsonValue.from(mapOf<String, Any>()))
        assertThat(userCreateResponse.tokenId()).contains("token_id")
        assertThat(userCreateResponse.tpmLimit()).contains(0L)
        assertThat(userCreateResponse.tpmLimitType())
            .contains(UserCreateResponse.TpmLimitType.GUARANTEED_THROUGHPUT)
        assertThat(userCreateResponse.updatedAt())
            .contains(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
        assertThat(userCreateResponse.updatedBy()).contains("updated_by")
        assertThat(userCreateResponse.userAlias()).contains("user_alias")
        assertThat(userCreateResponse.userEmail()).contains("user_email")
        assertThat(userCreateResponse.userId()).contains("user_id")
        assertThat(userCreateResponse.userRole()).contains(UserCreateResponse.UserRole.PROXY_ADMIN)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val userCreateResponse =
            UserCreateResponse.builder()
                .key("key")
                .token("token")
                .aliases(
                    UserCreateResponse.Aliases.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addAllowedCacheControl(JsonValue.from(mapOf<String, Any>()))
                .addAllowedPassthroughRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedRoute(JsonValue.from(mapOf<String, Any>()))
                .addAllowedVectorStoreIndex(
                    UserCreateResponse.AllowedVectorStoreIndex.builder()
                        .indexName("index_name")
                        .addIndexPermission(
                            UserCreateResponse.AllowedVectorStoreIndex.IndexPermission.READ
                        )
                        .build()
                )
                .blocked(true)
                .budgetDuration("budget_duration")
                .budgetId("budget_id")
                .config(
                    UserCreateResponse.Config.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .createdBy("created_by")
                .duration("duration")
                .addEnforcedParam("string")
                .expires(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .addGuardrail("string")
                .keyAlias("key_alias")
                .keyName("key_name")
                .litellmBudgetTable(JsonValue.from(mapOf<String, Any>()))
                .maxBudget(0.0)
                .maxParallelRequests(0L)
                .metadata(
                    UserCreateResponse.Metadata.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelMaxBudget(
                    UserCreateResponse.ModelMaxBudget.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelRpmLimit(
                    UserCreateResponse.ModelRpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .modelTpmLimit(
                    UserCreateResponse.ModelTpmLimit.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addModel(JsonValue.from(mapOf<String, Any>()))
                .objectPermission(
                    UserCreateResponse.ObjectPermission.builder()
                        .addAgentAccessGroup("string")
                        .addAgent("string")
                        .addMcpAccessGroup("string")
                        .addMcpServer("string")
                        .mcpToolPermissions(
                            UserCreateResponse.ObjectPermission.McpToolPermissions.builder()
                                .putAdditionalProperty("foo", JsonValue.from(listOf("string")))
                                .build()
                        )
                        .addVectorStore("string")
                        .build()
                )
                .organizationId("organization_id")
                .permissions(
                    UserCreateResponse.Permissions.builder()
                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                        .build()
                )
                .addPrompt("string")
                .routerSettings(
                    UserCreateResponse.RouterSettings.builder()
                        .allowedFails(0L)
                        .addContextWindowFallback(
                            UserCreateResponse.RouterSettings.ContextWindowFallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .cooldownTime(0.0)
                        .addFallback(
                            UserCreateResponse.RouterSettings.Fallback.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .maxRetries(0L)
                        .modelGroupAlias(
                            UserCreateResponse.RouterSettings.ModelGroupAlias.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .modelGroupRetryPolicy(
                            UserCreateResponse.RouterSettings.ModelGroupRetryPolicy.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .numRetries(0L)
                        .retryAfter(0.0)
                        .routingStrategy("routing_strategy")
                        .routingStrategyArgs(
                            UserCreateResponse.RouterSettings.RoutingStrategyArgs.builder()
                                .putAdditionalProperty("foo", JsonValue.from("bar"))
                                .build()
                        )
                        .timeout(0.0)
                        .build()
                )
                .rpmLimit(0L)
                .rpmLimitType(UserCreateResponse.RpmLimitType.GUARANTEED_THROUGHPUT)
                .spend(0.0)
                .addTag("string")
                .teamId("team_id")
                .addTeam(JsonValue.from(mapOf<String, Any>()))
                .tokenId("token_id")
                .tpmLimit(0L)
                .tpmLimitType(UserCreateResponse.TpmLimitType.GUARANTEED_THROUGHPUT)
                .updatedAt(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                .updatedBy("updated_by")
                .userAlias("user_alias")
                .userEmail("user_email")
                .userId("user_id")
                .userRole(UserCreateResponse.UserRole.PROXY_ADMIN)
                .build()

        val roundtrippedUserCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(userCreateResponse),
                jacksonTypeRef<UserCreateResponse>(),
            )

        assertThat(roundtrippedUserCreateResponse).isEqualTo(userCreateResponse)
    }
}
