/*
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import ai.hanzo.cloud.model.AuthoredPlugin;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * BuildOut
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class BuildOut {
  public static final String SERIALIZED_NAME_BYTES = "bytes";
  @SerializedName(SERIALIZED_NAME_BYTES)
  @javax.annotation.Nullable
  private Integer bytes;

  public static final String SERIALIZED_NAME_GENERATED = "generated";
  @SerializedName(SERIALIZED_NAME_GENERATED)
  @javax.annotation.Nullable
  private Boolean generated;

  public static final String SERIALIZED_NAME_PLUGIN = "plugin";
  @SerializedName(SERIALIZED_NAME_PLUGIN)
  @javax.annotation.Nullable
  private AuthoredPlugin plugin;

  public BuildOut() {
  }

  public BuildOut bytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
    return this;
  }

  /**
   * Get bytes
   * @return bytes
   */
  @javax.annotation.Nullable
  public Integer getBytes() {
    return bytes;
  }

  public void setBytes(@javax.annotation.Nullable Integer bytes) {
    this.bytes = bytes;
  }


  public BuildOut generated(@javax.annotation.Nullable Boolean generated) {
    this.generated = generated;
    return this;
  }

  /**
   * Get generated
   * @return generated
   */
  @javax.annotation.Nullable
  public Boolean getGenerated() {
    return generated;
  }

  public void setGenerated(@javax.annotation.Nullable Boolean generated) {
    this.generated = generated;
  }


  public BuildOut plugin(@javax.annotation.Nullable AuthoredPlugin plugin) {
    this.plugin = plugin;
    return this;
  }

  /**
   * Get plugin
   * @return plugin
   */
  @javax.annotation.Nullable
  public AuthoredPlugin getPlugin() {
    return plugin;
  }

  public void setPlugin(@javax.annotation.Nullable AuthoredPlugin plugin) {
    this.plugin = plugin;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BuildOut buildOut = (BuildOut) o;
    return Objects.equals(this.bytes, buildOut.bytes) &&
        Objects.equals(this.generated, buildOut.generated) &&
        Objects.equals(this.plugin, buildOut.plugin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bytes, generated, plugin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BuildOut {\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("    generated: ").append(toIndentedString(generated)).append("\n");
    sb.append("    plugin: ").append(toIndentedString(plugin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("bytes", "generated", "plugin"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BuildOut
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BuildOut.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BuildOut is not found in the empty JSON string", BuildOut.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BuildOut.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BuildOut` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `plugin`
      if (jsonObj.get("plugin") != null && !jsonObj.get("plugin").isJsonNull()) {
        AuthoredPlugin.validateJsonElement(jsonObj.get("plugin"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BuildOut.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BuildOut' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BuildOut> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BuildOut.class));

       return (TypeAdapter<T>) new TypeAdapter<BuildOut>() {
           @Override
           public void write(JsonWriter out, BuildOut value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BuildOut read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BuildOut given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BuildOut
   * @throws IOException if the JSON string is invalid with respect to BuildOut
   */
  public static BuildOut fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BuildOut.class);
  }

  /**
   * Convert an instance of BuildOut to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

