/*
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * CapturedError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CapturedError {
  public static final String SERIALIZED_NAME_DISTINCT_ID = "distinctId";
  @SerializedName(SERIALIZED_NAME_DISTINCT_ID)
  @javax.annotation.Nullable
  private String distinctId;

  public static final String SERIALIZED_NAME_EVENT = "event";
  @SerializedName(SERIALIZED_NAME_EVENT)
  @javax.annotation.Nullable
  private String event;

  public static final String SERIALIZED_NAME_EXCEPTION = "exception";
  @SerializedName(SERIALIZED_NAME_EXCEPTION)
  @javax.annotation.Nullable
  private Object exception = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private String id;

  public static final String SERIALIZED_NAME_LIBRARY = "library";
  @SerializedName(SERIALIZED_NAME_LIBRARY)
  @javax.annotation.Nullable
  private String library;

  public static final String SERIALIZED_NAME_LIBRARY_VERSION = "libraryVersion";
  @SerializedName(SERIALIZED_NAME_LIBRARY_VERSION)
  @javax.annotation.Nullable
  private String libraryVersion;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  @javax.annotation.Nullable
  private String path;

  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  @javax.annotation.Nullable
  private String product;

  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  @javax.annotation.Nullable
  private Object properties = null;

  public static final String SERIALIZED_NAME_SESSION_ID = "sessionId";
  @SerializedName(SERIALIZED_NAME_SESSION_ID)
  @javax.annotation.Nullable
  private String sessionId;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  @javax.annotation.Nullable
  private String timestamp;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nullable
  private String url;

  public CapturedError() {
  }

  public CapturedError distinctId(@javax.annotation.Nullable String distinctId) {
    this.distinctId = distinctId;
    return this;
  }

  /**
   * DistinctID is the person/visitor the error is attributed to. Omitted when the row carries none.
   * @return distinctId
   */
  @javax.annotation.Nullable
  public String getDistinctId() {
    return distinctId;
  }

  public void setDistinctId(@javax.annotation.Nullable String distinctId) {
    this.distinctId = distinctId;
  }


  public CapturedError event(@javax.annotation.Nullable String event) {
    this.event = event;
    return this;
  }

  /**
   * Event is the event name the error was stored under, e.g. $error.
   * @return event
   */
  @javax.annotation.Nullable
  public String getEvent() {
    return event;
  }

  public void setEvent(@javax.annotation.Nullable String event) {
    this.event = event;
  }


  public CapturedError exception(@javax.annotation.Nullable Object exception) {
    this.exception = exception;
    return this;
  }

  /**
   * Get exception
   * @return exception
   */
  @javax.annotation.Nullable
  public Object getException() {
    return exception;
  }

  public void setException(@javax.annotation.Nullable Object exception) {
    this.exception = exception;
  }


  public CapturedError id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * ID is the row&#39;s stable event id — the client&#39;s own idempotency id when it sent one, else the server-minted one.
   * @return id
   */
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public CapturedError library(@javax.annotation.Nullable String library) {
    this.library = library;
    return this;
  }

  /**
   * Library is the client SDK that reported the error. Omitted when absent.
   * @return library
   */
  @javax.annotation.Nullable
  public String getLibrary() {
    return library;
  }

  public void setLibrary(@javax.annotation.Nullable String library) {
    this.library = library;
  }


  public CapturedError libraryVersion(@javax.annotation.Nullable String libraryVersion) {
    this.libraryVersion = libraryVersion;
    return this;
  }

  /**
   * LibraryVer is that SDK&#39;s version. Omitted when absent.
   * @return libraryVersion
   */
  @javax.annotation.Nullable
  public String getLibraryVersion() {
    return libraryVersion;
  }

  public void setLibraryVersion(@javax.annotation.Nullable String libraryVersion) {
    this.libraryVersion = libraryVersion;
  }


  public CapturedError path(@javax.annotation.Nullable String path) {
    this.path = path;
    return this;
  }

  /**
   * Path is the URL&#39;s path component. Omitted when absent.
   * @return path
   */
  @javax.annotation.Nullable
  public String getPath() {
    return path;
  }

  public void setPath(@javax.annotation.Nullable String path) {
    this.path = path;
  }


  public CapturedError product(@javax.annotation.Nullable String product) {
    this.product = product;
    return this;
  }

  /**
   * Product is the surface that emitted the error. Omitted when absent.
   * @return product
   */
  @javax.annotation.Nullable
  public String getProduct() {
    return product;
  }

  public void setProduct(@javax.annotation.Nullable String product) {
    this.product = product;
  }


  public CapturedError properties(@javax.annotation.Nullable Object properties) {
    this.properties = properties;
    return this;
  }

  /**
   * Get properties
   * @return properties
   */
  @javax.annotation.Nullable
  public Object getProperties() {
    return properties;
  }

  public void setProperties(@javax.annotation.Nullable Object properties) {
    this.properties = properties;
  }


  public CapturedError sessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

  /**
   * SessionID groups the events of one visit. Omitted when the client sent none.
   * @return sessionId
   */
  @javax.annotation.Nullable
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(@javax.annotation.Nullable String sessionId) {
    this.sessionId = sessionId;
  }


  public CapturedError timestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
    return this;
  }

  /**
   * Timestamp is when the error was captured, RFC3339 UTC.
   * @return timestamp
   */
  @javax.annotation.Nullable
  public String getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(@javax.annotation.Nullable String timestamp) {
    this.timestamp = timestamp;
  }


  public CapturedError url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * URL is the full page address the error fired on. Omitted when absent.
   * @return url
   */
  @javax.annotation.Nullable
  public String getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CapturedError capturedError = (CapturedError) o;
    return Objects.equals(this.distinctId, capturedError.distinctId) &&
        Objects.equals(this.event, capturedError.event) &&
        Objects.equals(this.exception, capturedError.exception) &&
        Objects.equals(this.id, capturedError.id) &&
        Objects.equals(this.library, capturedError.library) &&
        Objects.equals(this.libraryVersion, capturedError.libraryVersion) &&
        Objects.equals(this.path, capturedError.path) &&
        Objects.equals(this.product, capturedError.product) &&
        Objects.equals(this.properties, capturedError.properties) &&
        Objects.equals(this.sessionId, capturedError.sessionId) &&
        Objects.equals(this.timestamp, capturedError.timestamp) &&
        Objects.equals(this.url, capturedError.url);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(distinctId, event, exception, id, library, libraryVersion, path, product, properties, sessionId, timestamp, url);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CapturedError {\n");
    sb.append("    distinctId: ").append(toIndentedString(distinctId)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    exception: ").append(toIndentedString(exception)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    library: ").append(toIndentedString(library)).append("\n");
    sb.append("    libraryVersion: ").append(toIndentedString(libraryVersion)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("distinctId", "event", "exception", "id", "library", "libraryVersion", "path", "product", "properties", "sessionId", "timestamp", "url"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CapturedError
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CapturedError.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CapturedError is not found in the empty JSON string", CapturedError.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CapturedError.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CapturedError` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("distinctId") != null && !jsonObj.get("distinctId").isJsonNull()) && !jsonObj.get("distinctId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `distinctId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("distinctId").toString()));
      }
      if ((jsonObj.get("event") != null && !jsonObj.get("event").isJsonNull()) && !jsonObj.get("event").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("library") != null && !jsonObj.get("library").isJsonNull()) && !jsonObj.get("library").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `library` to be a primitive type in the JSON string but got `%s`", jsonObj.get("library").toString()));
      }
      if ((jsonObj.get("libraryVersion") != null && !jsonObj.get("libraryVersion").isJsonNull()) && !jsonObj.get("libraryVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `libraryVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("libraryVersion").toString()));
      }
      if ((jsonObj.get("path") != null && !jsonObj.get("path").isJsonNull()) && !jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
      if ((jsonObj.get("product") != null && !jsonObj.get("product").isJsonNull()) && !jsonObj.get("product").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `product` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product").toString()));
      }
      if ((jsonObj.get("sessionId") != null && !jsonObj.get("sessionId").isJsonNull()) && !jsonObj.get("sessionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `sessionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sessionId").toString()));
      }
      if ((jsonObj.get("timestamp") != null && !jsonObj.get("timestamp").isJsonNull()) && !jsonObj.get("timestamp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timestamp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timestamp").toString()));
      }
      if ((jsonObj.get("url") != null && !jsonObj.get("url").isJsonNull()) && !jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CapturedError.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CapturedError' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CapturedError> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CapturedError.class));

       return (TypeAdapter<T>) new TypeAdapter<CapturedError>() {
           @Override
           public void write(JsonWriter out, CapturedError value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CapturedError read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CapturedError given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CapturedError
   * @throws IOException if the JSON string is invalid with respect to CapturedError
   */
  public static CapturedError fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CapturedError.class);
  }

  /**
   * Convert an instance of CapturedError to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

