/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import ai.hanzo.cloud.model.CloudGithubRepoView;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * CloudGithubReposOut
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CloudGithubReposOut {
  public static final String SERIALIZED_NAME_REPOS = "repos";
  @SerializedName(SERIALIZED_NAME_REPOS)
  @javax.annotation.Nullable
  private List<CloudGithubRepoView> repos = new ArrayList<>();

  public CloudGithubReposOut() {
  }

  public CloudGithubReposOut repos(@javax.annotation.Nullable List<CloudGithubRepoView> repos) {
    this.repos = repos;
    return this;
  }

  public CloudGithubReposOut addReposItem(CloudGithubRepoView reposItem) {
    if (this.repos == null) {
      this.repos = new ArrayList<>();
    }
    this.repos.add(reposItem);
    return this;
  }

  /**
   * Repos is every repo the installation grants. Never null; [] when none.
   * @return repos
   */
  @javax.annotation.Nullable
  public List<CloudGithubRepoView> getRepos() {
    return repos;
  }

  public void setRepos(@javax.annotation.Nullable List<CloudGithubRepoView> repos) {
    this.repos = repos;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudGithubReposOut cloudGithubReposOut = (CloudGithubReposOut) o;
    return Objects.equals(this.repos, cloudGithubReposOut.repos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(repos);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudGithubReposOut {\n");
    sb.append("    repos: ").append(toIndentedString(repos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("repos"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CloudGithubReposOut
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CloudGithubReposOut.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CloudGithubReposOut is not found in the empty JSON string", CloudGithubReposOut.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CloudGithubReposOut.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CloudGithubReposOut` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("repos") != null && !jsonObj.get("repos").isJsonNull()) {
        JsonArray jsonArrayrepos = jsonObj.getAsJsonArray("repos");
        if (jsonArrayrepos != null) {
          // ensure the json data is an array
          if (!jsonObj.get("repos").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `repos` to be an array in the JSON string but got `%s`", jsonObj.get("repos").toString()));
          }

          // validate the optional field `repos` (array)
          for (int i = 0; i < jsonArrayrepos.size(); i++) {
            CloudGithubRepoView.validateJsonElement(jsonArrayrepos.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CloudGithubReposOut.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CloudGithubReposOut' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CloudGithubReposOut> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CloudGithubReposOut.class));

       return (TypeAdapter<T>) new TypeAdapter<CloudGithubReposOut>() {
           @Override
           public void write(JsonWriter out, CloudGithubReposOut value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CloudGithubReposOut read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CloudGithubReposOut given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CloudGithubReposOut
   * @throws IOException if the JSON string is invalid with respect to CloudGithubReposOut
   */
  public static CloudGithubReposOut fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CloudGithubReposOut.class);
  }

  /**
   * Convert an instance of CloudGithubReposOut to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

