/*
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import ai.hanzo.cloud.model.ComplianceAccView;
import ai.hanzo.cloud.model.ComplianceCheckView;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * ComplianceRecordList
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ComplianceRecordList {
  public static final String SERIALIZED_NAME_ACCREDITATION = "accreditation";
  @SerializedName(SERIALIZED_NAME_ACCREDITATION)
  @javax.annotation.Nullable
  private List<ComplianceAccView> accreditation = new ArrayList<>();

  public static final String SERIALIZED_NAME_DISCLAIMER = "disclaimer";
  @SerializedName(SERIALIZED_NAME_DISCLAIMER)
  @javax.annotation.Nullable
  private String disclaimer;

  public static final String SERIALIZED_NAME_VERIFICATIONS = "verifications";
  @SerializedName(SERIALIZED_NAME_VERIFICATIONS)
  @javax.annotation.Nullable
  private List<ComplianceCheckView> verifications = new ArrayList<>();

  public ComplianceRecordList() {
  }

  public ComplianceRecordList accreditation(@javax.annotation.Nullable List<ComplianceAccView> accreditation) {
    this.accreditation = accreditation;
    return this;
  }

  public ComplianceRecordList addAccreditationItem(ComplianceAccView accreditationItem) {
    if (this.accreditation == null) {
      this.accreditation = new ArrayList<>();
    }
    this.accreditation.add(accreditationItem);
    return this;
  }

  /**
   * Accreditation is the org&#39;s tracked accreditation-state records.
   * @return accreditation
   */
  @javax.annotation.Nullable
  public List<ComplianceAccView> getAccreditation() {
    return accreditation;
  }

  public void setAccreditation(@javax.annotation.Nullable List<ComplianceAccView> accreditation) {
    this.accreditation = accreditation;
  }


  public ComplianceRecordList disclaimer(@javax.annotation.Nullable String disclaimer) {
    this.disclaimer = disclaimer;
    return this;
  }

  /**
   * Disclaimer states that statuses are provider-reported or tracked, never a platform assertion of legal or regulatory compliance.
   * @return disclaimer
   */
  @javax.annotation.Nullable
  public String getDisclaimer() {
    return disclaimer;
  }

  public void setDisclaimer(@javax.annotation.Nullable String disclaimer) {
    this.disclaimer = disclaimer;
  }


  public ComplianceRecordList verifications(@javax.annotation.Nullable List<ComplianceCheckView> verifications) {
    this.verifications = verifications;
    return this;
  }

  public ComplianceRecordList addVerificationsItem(ComplianceCheckView verificationsItem) {
    if (this.verifications == null) {
      this.verifications = new ArrayList<>();
    }
    this.verifications.add(verificationsItem);
    return this;
  }

  /**
   * Verifications is the org&#39;s KYC/KYB checks, provider-reported statuses only.
   * @return verifications
   */
  @javax.annotation.Nullable
  public List<ComplianceCheckView> getVerifications() {
    return verifications;
  }

  public void setVerifications(@javax.annotation.Nullable List<ComplianceCheckView> verifications) {
    this.verifications = verifications;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ComplianceRecordList instance itself
   */
  public ComplianceRecordList putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComplianceRecordList complianceRecordList = (ComplianceRecordList) o;
    return Objects.equals(this.accreditation, complianceRecordList.accreditation) &&
        Objects.equals(this.disclaimer, complianceRecordList.disclaimer) &&
        Objects.equals(this.verifications, complianceRecordList.verifications)&&
        Objects.equals(this.additionalProperties, complianceRecordList.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accreditation, disclaimer, verifications, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComplianceRecordList {\n");
    sb.append("    accreditation: ").append(toIndentedString(accreditation)).append("\n");
    sb.append("    disclaimer: ").append(toIndentedString(disclaimer)).append("\n");
    sb.append("    verifications: ").append(toIndentedString(verifications)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("accreditation", "disclaimer", "verifications"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ComplianceRecordList
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ComplianceRecordList.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ComplianceRecordList is not found in the empty JSON string", ComplianceRecordList.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("accreditation") != null && !jsonObj.get("accreditation").isJsonNull()) {
        JsonArray jsonArrayaccreditation = jsonObj.getAsJsonArray("accreditation");
        if (jsonArrayaccreditation != null) {
          // ensure the json data is an array
          if (!jsonObj.get("accreditation").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `accreditation` to be an array in the JSON string but got `%s`", jsonObj.get("accreditation").toString()));
          }

          // validate the optional field `accreditation` (array)
          for (int i = 0; i < jsonArrayaccreditation.size(); i++) {
            ComplianceAccView.validateJsonElement(jsonArrayaccreditation.get(i));
          };
        }
      }
      if ((jsonObj.get("disclaimer") != null && !jsonObj.get("disclaimer").isJsonNull()) && !jsonObj.get("disclaimer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `disclaimer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("disclaimer").toString()));
      }
      if (jsonObj.get("verifications") != null && !jsonObj.get("verifications").isJsonNull()) {
        JsonArray jsonArrayverifications = jsonObj.getAsJsonArray("verifications");
        if (jsonArrayverifications != null) {
          // ensure the json data is an array
          if (!jsonObj.get("verifications").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `verifications` to be an array in the JSON string but got `%s`", jsonObj.get("verifications").toString()));
          }

          // validate the optional field `verifications` (array)
          for (int i = 0; i < jsonArrayverifications.size(); i++) {
            ComplianceCheckView.validateJsonElement(jsonArrayverifications.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ComplianceRecordList.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ComplianceRecordList' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ComplianceRecordList> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ComplianceRecordList.class));

       return (TypeAdapter<T>) new TypeAdapter<ComplianceRecordList>() {
           @Override
           public void write(JsonWriter out, ComplianceRecordList value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ComplianceRecordList read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             ComplianceRecordList instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ComplianceRecordList given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ComplianceRecordList
   * @throws IOException if the JSON string is invalid with respect to ComplianceRecordList
   */
  public static ComplianceRecordList fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ComplianceRecordList.class);
  }

  /**
   * Convert an instance of ComplianceRecordList to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

