/*
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * GraphGraphCommunitiesIn
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class GraphGraphCommunitiesIn {
  public static final String SERIALIZED_NAME_AS_KNOWN = "as_known";
  @SerializedName(SERIALIZED_NAME_AS_KNOWN)
  @javax.annotation.Nullable
  private String asKnown;

  public static final String SERIALIZED_NAME_AS_OF = "as_of";
  @SerializedName(SERIALIZED_NAME_AS_OF)
  @javax.annotation.Nullable
  private String asOf;

  public static final String SERIALIZED_NAME_LEVEL = "level";
  @SerializedName(SERIALIZED_NAME_LEVEL)
  @javax.annotation.Nullable
  private Long level;

  public static final String SERIALIZED_NAME_RELATION = "relation";
  @SerializedName(SERIALIZED_NAME_RELATION)
  @javax.annotation.Nullable
  private String relation;

  public GraphGraphCommunitiesIn() {
  }

  public GraphGraphCommunitiesIn asKnown(@javax.annotation.Nullable String asKnown) {
    this.asKnown = asKnown;
    return this;
  }

  /**
   * AsKnown is how much this plane had heard, RFC 3339: the answer as it would have been given then, which is what makes a past answer reproducible. Absent is now.
   * @return asKnown
   */
  @javax.annotation.Nullable
  public String getAsKnown() {
    return asKnown;
  }

  public void setAsKnown(@javax.annotation.Nullable String asKnown) {
    this.asKnown = asKnown;
  }


  public GraphGraphCommunitiesIn asOf(@javax.annotation.Nullable String asOf) {
    this.asOf = asOf;
    return this;
  }

  /**
   * AsOf partitions the graph as it stood at an instant of the world, RFC 3339: the edges that held then. Absent is now.
   * @return asOf
   */
  @javax.annotation.Nullable
  public String getAsOf() {
    return asOf;
  }

  public void setAsOf(@javax.annotation.Nullable String asOf) {
    this.asOf = asOf;
  }


  public GraphGraphCommunitiesIn level(@javax.annotation.Nullable Long level) {
    this.level = level;
    return this;
  }

  /**
   * Level is how fine a partition to answer with. 0, the default, is the coarsest — the partition detection stops at, where modularity is highest — and each level above it is the pass before, finer. &#x60;levels&#x60; in the answer says how many there are.
   * @return level
   */
  @javax.annotation.Nullable
  public Long getLevel() {
    return level;
  }

  public void setLevel(@javax.annotation.Nullable Long level) {
    this.level = level;
  }


  public GraphGraphCommunitiesIn relation(@javax.annotation.Nullable String relation) {
    this.relation = relation;
    return this;
  }

  /**
   * Relation narrows the graph to one edge relation, by its key. Absent partitions every edge.
   * @return relation
   */
  @javax.annotation.Nullable
  public String getRelation() {
    return relation;
  }

  public void setRelation(@javax.annotation.Nullable String relation) {
    this.relation = relation;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GraphGraphCommunitiesIn instance itself
   */
  public GraphGraphCommunitiesIn putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GraphGraphCommunitiesIn graphGraphCommunitiesIn = (GraphGraphCommunitiesIn) o;
    return Objects.equals(this.asKnown, graphGraphCommunitiesIn.asKnown) &&
        Objects.equals(this.asOf, graphGraphCommunitiesIn.asOf) &&
        Objects.equals(this.level, graphGraphCommunitiesIn.level) &&
        Objects.equals(this.relation, graphGraphCommunitiesIn.relation)&&
        Objects.equals(this.additionalProperties, graphGraphCommunitiesIn.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(asKnown, asOf, level, relation, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GraphGraphCommunitiesIn {\n");
    sb.append("    asKnown: ").append(toIndentedString(asKnown)).append("\n");
    sb.append("    asOf: ").append(toIndentedString(asOf)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    relation: ").append(toIndentedString(relation)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("as_known", "as_of", "level", "relation"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GraphGraphCommunitiesIn
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GraphGraphCommunitiesIn.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GraphGraphCommunitiesIn is not found in the empty JSON string", GraphGraphCommunitiesIn.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("as_known") != null && !jsonObj.get("as_known").isJsonNull()) && !jsonObj.get("as_known").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `as_known` to be a primitive type in the JSON string but got `%s`", jsonObj.get("as_known").toString()));
      }
      if ((jsonObj.get("as_of") != null && !jsonObj.get("as_of").isJsonNull()) && !jsonObj.get("as_of").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `as_of` to be a primitive type in the JSON string but got `%s`", jsonObj.get("as_of").toString()));
      }
      if ((jsonObj.get("relation") != null && !jsonObj.get("relation").isJsonNull()) && !jsonObj.get("relation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `relation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("relation").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GraphGraphCommunitiesIn.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GraphGraphCommunitiesIn' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GraphGraphCommunitiesIn> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GraphGraphCommunitiesIn.class));

       return (TypeAdapter<T>) new TypeAdapter<GraphGraphCommunitiesIn>() {
           @Override
           public void write(JsonWriter out, GraphGraphCommunitiesIn value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GraphGraphCommunitiesIn read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             GraphGraphCommunitiesIn instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GraphGraphCommunitiesIn given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GraphGraphCommunitiesIn
   * @throws IOException if the JSON string is invalid with respect to GraphGraphCommunitiesIn
   */
  public static GraphGraphCommunitiesIn fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GraphGraphCommunitiesIn.class);
  }

  /**
   * Convert an instance of GraphGraphCommunitiesIn to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

