/*
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * IndexCount
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class IndexCount {
  public static final String SERIALIZED_NAME_IS_INDEXING = "isIndexing";
  @SerializedName(SERIALIZED_NAME_IS_INDEXING)
  @javax.annotation.Nullable
  private Boolean isIndexing;

  public static final String SERIALIZED_NAME_NUMBER_OF_DOCUMENTS = "numberOfDocuments";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_DOCUMENTS)
  @javax.annotation.Nullable
  private Integer numberOfDocuments;

  public IndexCount() {
  }

  public IndexCount isIndexing(@javax.annotation.Nullable Boolean isIndexing) {
    this.isIndexing = isIndexing;
    return this;
  }

  /**
   * IsIndexing is always false: writes are applied before their response, so there is never a background pass a caller could be waiting on.
   * @return isIndexing
   */
  @javax.annotation.Nullable
  public Boolean getIsIndexing() {
    return isIndexing;
  }

  public void setIsIndexing(@javax.annotation.Nullable Boolean isIndexing) {
    this.isIndexing = isIndexing;
  }


  public IndexCount numberOfDocuments(@javax.annotation.Nullable Integer numberOfDocuments) {
    this.numberOfDocuments = numberOfDocuments;
    return this;
  }

  /**
   * NumberOfDocuments is how many documents this org holds in that index.
   * @return numberOfDocuments
   */
  @javax.annotation.Nullable
  public Integer getNumberOfDocuments() {
    return numberOfDocuments;
  }

  public void setNumberOfDocuments(@javax.annotation.Nullable Integer numberOfDocuments) {
    this.numberOfDocuments = numberOfDocuments;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndexCount indexCount = (IndexCount) o;
    return Objects.equals(this.isIndexing, indexCount.isIndexing) &&
        Objects.equals(this.numberOfDocuments, indexCount.numberOfDocuments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isIndexing, numberOfDocuments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndexCount {\n");
    sb.append("    isIndexing: ").append(toIndentedString(isIndexing)).append("\n");
    sb.append("    numberOfDocuments: ").append(toIndentedString(numberOfDocuments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("isIndexing", "numberOfDocuments"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IndexCount
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IndexCount.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in IndexCount is not found in the empty JSON string", IndexCount.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IndexCount.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `IndexCount` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IndexCount.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IndexCount' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IndexCount> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IndexCount.class));

       return (TypeAdapter<T>) new TypeAdapter<IndexCount>() {
           @Override
           public void write(JsonWriter out, IndexCount value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IndexCount read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IndexCount given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IndexCount
   * @throws IOException if the JSON string is invalid with respect to IndexCount
   */
  public static IndexCount fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IndexCount.class);
  }

  /**
   * Convert an instance of IndexCount to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

