/*
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import ai.hanzo.cloud.model.MarketToken;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * MarketPool
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MarketPool {
  public static final String SERIALIZED_NAME_AT = "at";
  @SerializedName(SERIALIZED_NAME_AT)
  @javax.annotation.Nullable
  private String at;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  @javax.annotation.Nullable
  private Long count;

  public static final String SERIALIZED_NAME_FEE = "fee";
  @SerializedName(SERIALIZED_NAME_FEE)
  @javax.annotation.Nullable
  private Long fee;

  public static final String SERIALIZED_NAME_LOCKED = "locked";
  @SerializedName(SERIALIZED_NAME_LOCKED)
  @javax.annotation.Nullable
  private String locked;

  public static final String SERIALIZED_NAME_TOKEN0 = "token0";
  @SerializedName(SERIALIZED_NAME_TOKEN0)
  @javax.annotation.Nullable
  private MarketToken token0;

  public static final String SERIALIZED_NAME_TOKEN0_PRICE = "token0Price";
  @SerializedName(SERIALIZED_NAME_TOKEN0_PRICE)
  @javax.annotation.Nullable
  private String token0Price;

  public static final String SERIALIZED_NAME_TOKEN1 = "token1";
  @SerializedName(SERIALIZED_NAME_TOKEN1)
  @javax.annotation.Nullable
  private MarketToken token1;

  public static final String SERIALIZED_NAME_TOKEN1_PRICE = "token1Price";
  @SerializedName(SERIALIZED_NAME_TOKEN1_PRICE)
  @javax.annotation.Nullable
  private String token1Price;

  public static final String SERIALIZED_NAME_VOLUME = "volume";
  @SerializedName(SERIALIZED_NAME_VOLUME)
  @javax.annotation.Nullable
  private String volume;

  public MarketPool() {
  }

  public MarketPool at(@javax.annotation.Nullable String at) {
    this.at = at;
    return this;
  }

  /**
   * At is the pool contract&#39;s address, lowercase.
   * @return at
   */
  @javax.annotation.Nullable
  public String getAt() {
    return at;
  }

  public void setAt(@javax.annotation.Nullable String at) {
    this.at = at;
  }


  public MarketPool count(@javax.annotation.Nullable Long count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   */
  @javax.annotation.Nullable
  public Long getCount() {
    return count;
  }

  public void setCount(@javax.annotation.Nullable Long count) {
    this.count = count;
  }


  public MarketPool fee(@javax.annotation.Nullable Long fee) {
    this.fee = fee;
    return this;
  }

  /**
   * Fee is the pool&#39;s tier in hundredths of a basis point — 3000 is 0.3%. It is the integer the contract stores, unconverted, so nothing here rounds a rate.
   * @return fee
   */
  @javax.annotation.Nullable
  public Long getFee() {
    return fee;
  }

  public void setFee(@javax.annotation.Nullable Long fee) {
    this.fee = fee;
  }


  public MarketPool locked(@javax.annotation.Nullable String locked) {
    this.locked = locked;
    return this;
  }

  /**
   * Get locked
   * @return locked
   */
  @javax.annotation.Nullable
  public String getLocked() {
    return locked;
  }

  public void setLocked(@javax.annotation.Nullable String locked) {
    this.locked = locked;
  }


  public MarketPool token0(@javax.annotation.Nullable MarketToken token0) {
    this.token0 = token0;
    return this;
  }

  /**
   * Get token0
   * @return token0
   */
  @javax.annotation.Nullable
  public MarketToken getToken0() {
    return token0;
  }

  public void setToken0(@javax.annotation.Nullable MarketToken token0) {
    this.token0 = token0;
  }


  public MarketPool token0Price(@javax.annotation.Nullable String token0Price) {
    this.token0Price = token0Price;
    return this;
  }

  /**
   * Token0Price is token1 per token0, and Token1Price its reciprocal, both as the indexer computed them. Neither is a price ON anything: it is the ratio the pool&#39;s reserves stand at.
   * @return token0Price
   */
  @javax.annotation.Nullable
  public String getToken0Price() {
    return token0Price;
  }

  public void setToken0Price(@javax.annotation.Nullable String token0Price) {
    this.token0Price = token0Price;
  }


  public MarketPool token1(@javax.annotation.Nullable MarketToken token1) {
    this.token1 = token1;
    return this;
  }

  /**
   * Get token1
   * @return token1
   */
  @javax.annotation.Nullable
  public MarketToken getToken1() {
    return token1;
  }

  public void setToken1(@javax.annotation.Nullable MarketToken token1) {
    this.token1 = token1;
  }


  public MarketPool token1Price(@javax.annotation.Nullable String token1Price) {
    this.token1Price = token1Price;
    return this;
  }

  /**
   * Get token1Price
   * @return token1Price
   */
  @javax.annotation.Nullable
  public String getToken1Price() {
    return token1Price;
  }

  public void setToken1Price(@javax.annotation.Nullable String token1Price) {
    this.token1Price = token1Price;
  }


  public MarketPool volume(@javax.annotation.Nullable String volume) {
    this.volume = volume;
    return this;
  }

  /**
   * Get volume
   * @return volume
   */
  @javax.annotation.Nullable
  public String getVolume() {
    return volume;
  }

  public void setVolume(@javax.annotation.Nullable String volume) {
    this.volume = volume;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the MarketPool instance itself
   */
  public MarketPool putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketPool marketPool = (MarketPool) o;
    return Objects.equals(this.at, marketPool.at) &&
        Objects.equals(this.count, marketPool.count) &&
        Objects.equals(this.fee, marketPool.fee) &&
        Objects.equals(this.locked, marketPool.locked) &&
        Objects.equals(this.token0, marketPool.token0) &&
        Objects.equals(this.token0Price, marketPool.token0Price) &&
        Objects.equals(this.token1, marketPool.token1) &&
        Objects.equals(this.token1Price, marketPool.token1Price) &&
        Objects.equals(this.volume, marketPool.volume)&&
        Objects.equals(this.additionalProperties, marketPool.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(at, count, fee, locked, token0, token0Price, token1, token1Price, volume, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketPool {\n");
    sb.append("    at: ").append(toIndentedString(at)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    token0: ").append(toIndentedString(token0)).append("\n");
    sb.append("    token0Price: ").append(toIndentedString(token0Price)).append("\n");
    sb.append("    token1: ").append(toIndentedString(token1)).append("\n");
    sb.append("    token1Price: ").append(toIndentedString(token1Price)).append("\n");
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("at", "count", "fee", "locked", "token0", "token0Price", "token1", "token1Price", "volume"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MarketPool
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MarketPool.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MarketPool is not found in the empty JSON string", MarketPool.openapiRequiredFields.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("at") != null && !jsonObj.get("at").isJsonNull()) && !jsonObj.get("at").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `at` to be a primitive type in the JSON string but got `%s`", jsonObj.get("at").toString()));
      }
      if ((jsonObj.get("locked") != null && !jsonObj.get("locked").isJsonNull()) && !jsonObj.get("locked").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `locked` to be a primitive type in the JSON string but got `%s`", jsonObj.get("locked").toString()));
      }
      // validate the optional field `token0`
      if (jsonObj.get("token0") != null && !jsonObj.get("token0").isJsonNull()) {
        MarketToken.validateJsonElement(jsonObj.get("token0"));
      }
      if ((jsonObj.get("token0Price") != null && !jsonObj.get("token0Price").isJsonNull()) && !jsonObj.get("token0Price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token0Price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token0Price").toString()));
      }
      // validate the optional field `token1`
      if (jsonObj.get("token1") != null && !jsonObj.get("token1").isJsonNull()) {
        MarketToken.validateJsonElement(jsonObj.get("token1"));
      }
      if ((jsonObj.get("token1Price") != null && !jsonObj.get("token1Price").isJsonNull()) && !jsonObj.get("token1Price").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `token1Price` to be a primitive type in the JSON string but got `%s`", jsonObj.get("token1Price").toString()));
      }
      if ((jsonObj.get("volume") != null && !jsonObj.get("volume").isJsonNull()) && !jsonObj.get("volume").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `volume` to be a primitive type in the JSON string but got `%s`", jsonObj.get("volume").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MarketPool.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MarketPool' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MarketPool> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MarketPool.class));

       return (TypeAdapter<T>) new TypeAdapter<MarketPool>() {
           @Override
           public void write(JsonWriter out, MarketPool value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public MarketPool read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             MarketPool instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MarketPool given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MarketPool
   * @throws IOException if the JSON string is invalid with respect to MarketPool
   */
  public static MarketPool fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MarketPool.class);
  }

  /**
   * Convert an instance of MarketPool to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

