/*
 * Hanzo Cloud API
 * The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * O11yO11yReductionStats
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class O11yO11yReductionStats {
  public static final String SERIALIZED_NAME_ESTIMATED_MONTHLY_SAVINGS_USD = "estimatedMonthlySavingsUsd";
  @SerializedName(SERIALIZED_NAME_ESTIMATED_MONTHLY_SAVINGS_USD)
  @javax.annotation.Nullable
  private Double estimatedMonthlySavingsUsd;

  public static final String SERIALIZED_NAME_INGESTED_SAMPLES = "ingestedSamples";
  @SerializedName(SERIALIZED_NAME_INGESTED_SAMPLES)
  @javax.annotation.Nullable
  private Integer ingestedSamples;

  public static final String SERIALIZED_NAME_INGESTED_SERIES = "ingestedSeries";
  @SerializedName(SERIALIZED_NAME_INGESTED_SERIES)
  @javax.annotation.Nullable
  private Integer ingestedSeries;

  public static final String SERIALIZED_NAME_RETAINED_SAMPLES = "retainedSamples";
  @SerializedName(SERIALIZED_NAME_RETAINED_SAMPLES)
  @javax.annotation.Nullable
  private Integer retainedSamples;

  public static final String SERIALIZED_NAME_RETAINED_SERIES = "retainedSeries";
  @SerializedName(SERIALIZED_NAME_RETAINED_SERIES)
  @javax.annotation.Nullable
  private Integer retainedSeries;

  public O11yO11yReductionStats() {
  }

  public O11yO11yReductionStats estimatedMonthlySavingsUsd(@javax.annotation.Nullable Double estimatedMonthlySavingsUsd) {
    this.estimatedMonthlySavingsUsd = estimatedMonthlySavingsUsd;
    return this;
  }

  /**
   * EstimatedMonthlySavingsUsd is the estimated monthly savings, in USD.
   * @return estimatedMonthlySavingsUsd
   */
  @javax.annotation.Nullable
  public Double getEstimatedMonthlySavingsUsd() {
    return estimatedMonthlySavingsUsd;
  }

  public void setEstimatedMonthlySavingsUsd(@javax.annotation.Nullable Double estimatedMonthlySavingsUsd) {
    this.estimatedMonthlySavingsUsd = estimatedMonthlySavingsUsd;
  }


  public O11yO11yReductionStats ingestedSamples(@javax.annotation.Nullable Integer ingestedSamples) {
    this.ingestedSamples = ingestedSamples;
    return this;
  }

  /**
   * IngestedSamples is how many samples arrived across all rules.
   * @return ingestedSamples
   */
  @javax.annotation.Nullable
  public Integer getIngestedSamples() {
    return ingestedSamples;
  }

  public void setIngestedSamples(@javax.annotation.Nullable Integer ingestedSamples) {
    this.ingestedSamples = ingestedSamples;
  }


  public O11yO11yReductionStats ingestedSeries(@javax.annotation.Nullable Integer ingestedSeries) {
    this.ingestedSeries = ingestedSeries;
    return this;
  }

  /**
   * IngestedSeries is how many series arrived across all rules.
   * @return ingestedSeries
   */
  @javax.annotation.Nullable
  public Integer getIngestedSeries() {
    return ingestedSeries;
  }

  public void setIngestedSeries(@javax.annotation.Nullable Integer ingestedSeries) {
    this.ingestedSeries = ingestedSeries;
  }


  public O11yO11yReductionStats retainedSamples(@javax.annotation.Nullable Integer retainedSamples) {
    this.retainedSamples = retainedSamples;
    return this;
  }

  /**
   * RetainedSamples is how many of them were kept.
   * @return retainedSamples
   */
  @javax.annotation.Nullable
  public Integer getRetainedSamples() {
    return retainedSamples;
  }

  public void setRetainedSamples(@javax.annotation.Nullable Integer retainedSamples) {
    this.retainedSamples = retainedSamples;
  }


  public O11yO11yReductionStats retainedSeries(@javax.annotation.Nullable Integer retainedSeries) {
    this.retainedSeries = retainedSeries;
    return this;
  }

  /**
   * RetainedSeries is how many of them were kept.
   * @return retainedSeries
   */
  @javax.annotation.Nullable
  public Integer getRetainedSeries() {
    return retainedSeries;
  }

  public void setRetainedSeries(@javax.annotation.Nullable Integer retainedSeries) {
    this.retainedSeries = retainedSeries;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    O11yO11yReductionStats o11yO11yReductionStats = (O11yO11yReductionStats) o;
    return Objects.equals(this.estimatedMonthlySavingsUsd, o11yO11yReductionStats.estimatedMonthlySavingsUsd) &&
        Objects.equals(this.ingestedSamples, o11yO11yReductionStats.ingestedSamples) &&
        Objects.equals(this.ingestedSeries, o11yO11yReductionStats.ingestedSeries) &&
        Objects.equals(this.retainedSamples, o11yO11yReductionStats.retainedSamples) &&
        Objects.equals(this.retainedSeries, o11yO11yReductionStats.retainedSeries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(estimatedMonthlySavingsUsd, ingestedSamples, ingestedSeries, retainedSamples, retainedSeries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class O11yO11yReductionStats {\n");
    sb.append("    estimatedMonthlySavingsUsd: ").append(toIndentedString(estimatedMonthlySavingsUsd)).append("\n");
    sb.append("    ingestedSamples: ").append(toIndentedString(ingestedSamples)).append("\n");
    sb.append("    ingestedSeries: ").append(toIndentedString(ingestedSeries)).append("\n");
    sb.append("    retainedSamples: ").append(toIndentedString(retainedSamples)).append("\n");
    sb.append("    retainedSeries: ").append(toIndentedString(retainedSeries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("estimatedMonthlySavingsUsd", "ingestedSamples", "ingestedSeries", "retainedSamples", "retainedSeries"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to O11yO11yReductionStats
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!O11yO11yReductionStats.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in O11yO11yReductionStats is not found in the empty JSON string", O11yO11yReductionStats.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!O11yO11yReductionStats.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `O11yO11yReductionStats` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!O11yO11yReductionStats.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'O11yO11yReductionStats' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<O11yO11yReductionStats> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(O11yO11yReductionStats.class));

       return (TypeAdapter<T>) new TypeAdapter<O11yO11yReductionStats>() {
           @Override
           public void write(JsonWriter out, O11yO11yReductionStats value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public O11yO11yReductionStats read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of O11yO11yReductionStats given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of O11yO11yReductionStats
   * @throws IOException if the JSON string is invalid with respect to O11yO11yReductionStats
   */
  public static O11yO11yReductionStats fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, O11yO11yReductionStats.class);
  }

  /**
   * Convert an instance of O11yO11yReductionStats to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

