/*
 * Hanzo Cloud API
 * Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import ai.hanzo.cloud.model.O11yDeployment;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * O11yStatusResult
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class O11yStatusResult {
  public static final String SERIALIZED_NAME_CHECKED_AT = "checkedAt";
  @SerializedName(SERIALIZED_NAME_CHECKED_AT)
  @javax.annotation.Nullable
  private String checkedAt;

  public static final String SERIALIZED_NAME_DEPLOYMENTS = "deployments";
  @SerializedName(SERIALIZED_NAME_DEPLOYMENTS)
  @javax.annotation.Nullable
  private List<O11yDeployment> deployments = new ArrayList<>();

  public static final String SERIALIZED_NAME_LATENCY_MS = "latencyMs";
  @SerializedName(SERIALIZED_NAME_LATENCY_MS)
  @javax.annotation.Nullable
  private Integer latencyMs;

  public static final String SERIALIZED_NAME_PRODUCT = "product";
  @SerializedName(SERIALIZED_NAME_PRODUCT)
  @javax.annotation.Nullable
  private String product;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  @javax.annotation.Nullable
  private String source;

  public static final String SERIALIZED_NAME_UP = "up";
  @SerializedName(SERIALIZED_NAME_UP)
  @javax.annotation.Nullable
  private Boolean up;

  public O11yStatusResult() {
  }

  public O11yStatusResult checkedAt(@javax.annotation.Nullable String checkedAt) {
    this.checkedAt = checkedAt;
    return this;
  }

  /**
   * Get checkedAt
   * @return checkedAt
   */
  @javax.annotation.Nullable
  public String getCheckedAt() {
    return checkedAt;
  }

  public void setCheckedAt(@javax.annotation.Nullable String checkedAt) {
    this.checkedAt = checkedAt;
  }


  public O11yStatusResult deployments(@javax.annotation.Nullable List<O11yDeployment> deployments) {
    this.deployments = deployments;
    return this;
  }

  public O11yStatusResult addDeploymentsItem(O11yDeployment deploymentsItem) {
    if (this.deployments == null) {
      this.deployments = new ArrayList<>();
    }
    this.deployments.add(deploymentsItem);
    return this;
  }

  /**
   * Get deployments
   * @return deployments
   */
  @javax.annotation.Nullable
  public List<O11yDeployment> getDeployments() {
    return deployments;
  }

  public void setDeployments(@javax.annotation.Nullable List<O11yDeployment> deployments) {
    this.deployments = deployments;
  }


  public O11yStatusResult latencyMs(@javax.annotation.Nullable Integer latencyMs) {
    this.latencyMs = latencyMs;
    return this;
  }

  /**
   * Get latencyMs
   * @return latencyMs
   */
  @javax.annotation.Nullable
  public Integer getLatencyMs() {
    return latencyMs;
  }

  public void setLatencyMs(@javax.annotation.Nullable Integer latencyMs) {
    this.latencyMs = latencyMs;
  }


  public O11yStatusResult product(@javax.annotation.Nullable String product) {
    this.product = product;
    return this;
  }

  /**
   * Get product
   * @return product
   */
  @javax.annotation.Nullable
  public String getProduct() {
    return product;
  }

  public void setProduct(@javax.annotation.Nullable String product) {
    this.product = product;
  }


  public O11yStatusResult source(@javax.annotation.Nullable String source) {
    this.source = source;
    return this;
  }

  /**
   * Get source
   * @return source
   */
  @javax.annotation.Nullable
  public String getSource() {
    return source;
  }

  public void setSource(@javax.annotation.Nullable String source) {
    this.source = source;
  }


  public O11yStatusResult up(@javax.annotation.Nullable Boolean up) {
    this.up = up;
    return this;
  }

  /**
   * Get up
   * @return up
   */
  @javax.annotation.Nullable
  public Boolean getUp() {
    return up;
  }

  public void setUp(@javax.annotation.Nullable Boolean up) {
    this.up = up;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    O11yStatusResult o11yStatusResult = (O11yStatusResult) o;
    return Objects.equals(this.checkedAt, o11yStatusResult.checkedAt) &&
        Objects.equals(this.deployments, o11yStatusResult.deployments) &&
        Objects.equals(this.latencyMs, o11yStatusResult.latencyMs) &&
        Objects.equals(this.product, o11yStatusResult.product) &&
        Objects.equals(this.source, o11yStatusResult.source) &&
        Objects.equals(this.up, o11yStatusResult.up);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkedAt, deployments, latencyMs, product, source, up);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class O11yStatusResult {\n");
    sb.append("    checkedAt: ").append(toIndentedString(checkedAt)).append("\n");
    sb.append("    deployments: ").append(toIndentedString(deployments)).append("\n");
    sb.append("    latencyMs: ").append(toIndentedString(latencyMs)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    up: ").append(toIndentedString(up)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("checkedAt", "deployments", "latencyMs", "product", "source", "up"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to O11yStatusResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!O11yStatusResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in O11yStatusResult is not found in the empty JSON string", O11yStatusResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!O11yStatusResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `O11yStatusResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("checkedAt") != null && !jsonObj.get("checkedAt").isJsonNull()) && !jsonObj.get("checkedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `checkedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("checkedAt").toString()));
      }
      if (jsonObj.get("deployments") != null && !jsonObj.get("deployments").isJsonNull()) {
        JsonArray jsonArraydeployments = jsonObj.getAsJsonArray("deployments");
        if (jsonArraydeployments != null) {
          // ensure the json data is an array
          if (!jsonObj.get("deployments").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `deployments` to be an array in the JSON string but got `%s`", jsonObj.get("deployments").toString()));
          }

          // validate the optional field `deployments` (array)
          for (int i = 0; i < jsonArraydeployments.size(); i++) {
            O11yDeployment.validateJsonElement(jsonArraydeployments.get(i));
          };
        }
      }
      if ((jsonObj.get("product") != null && !jsonObj.get("product").isJsonNull()) && !jsonObj.get("product").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `product` to be a primitive type in the JSON string but got `%s`", jsonObj.get("product").toString()));
      }
      if ((jsonObj.get("source") != null && !jsonObj.get("source").isJsonNull()) && !jsonObj.get("source").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!O11yStatusResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'O11yStatusResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<O11yStatusResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(O11yStatusResult.class));

       return (TypeAdapter<T>) new TypeAdapter<O11yStatusResult>() {
           @Override
           public void write(JsonWriter out, O11yStatusResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public O11yStatusResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of O11yStatusResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of O11yStatusResult
   * @throws IOException if the JSON string is invalid with respect to O11yStatusResult
   */
  public static O11yStatusResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, O11yStatusResult.class);
  }

  /**
   * Convert an instance of O11yStatusResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

