/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * SearchSettingsFaceting
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SearchSettingsFaceting {
  public static final String SERIALIZED_NAME_MAX_VALUES_PER_FACET = "maxValuesPerFacet";
  @SerializedName(SERIALIZED_NAME_MAX_VALUES_PER_FACET)
  @javax.annotation.Nullable
  private Integer maxValuesPerFacet;

  /**
   * Gets or Sets inner
   */
  @JsonAdapter(InnerEnum.Adapter.class)
  public enum InnerEnum {
    ALPHA("alpha"),
    
    COUNT("count");

    private String value;

    InnerEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static InnerEnum fromValue(String value) {
      for (InnerEnum b : InnerEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<InnerEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final InnerEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public InnerEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return InnerEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      InnerEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_SORT_FACET_VALUES_BY = "sortFacetValuesBy";
  @SerializedName(SERIALIZED_NAME_SORT_FACET_VALUES_BY)
  @javax.annotation.Nullable
  private Map<String, InnerEnum> sortFacetValuesBy = new HashMap<>();

  public SearchSettingsFaceting() {
  }

  public SearchSettingsFaceting maxValuesPerFacet(@javax.annotation.Nullable Integer maxValuesPerFacet) {
    this.maxValuesPerFacet = maxValuesPerFacet;
    return this;
  }

  /**
   * Get maxValuesPerFacet
   * @return maxValuesPerFacet
   */
  @javax.annotation.Nullable
  public Integer getMaxValuesPerFacet() {
    return maxValuesPerFacet;
  }

  public void setMaxValuesPerFacet(@javax.annotation.Nullable Integer maxValuesPerFacet) {
    this.maxValuesPerFacet = maxValuesPerFacet;
  }


  public SearchSettingsFaceting sortFacetValuesBy(@javax.annotation.Nullable Map<String, InnerEnum> sortFacetValuesBy) {
    this.sortFacetValuesBy = sortFacetValuesBy;
    return this;
  }

  public SearchSettingsFaceting putSortFacetValuesByItem(String key, InnerEnum sortFacetValuesByItem) {
    if (this.sortFacetValuesBy == null) {
      this.sortFacetValuesBy = new HashMap<>();
    }
    this.sortFacetValuesBy.put(key, sortFacetValuesByItem);
    return this;
  }

  /**
   * Get sortFacetValuesBy
   * @return sortFacetValuesBy
   */
  @javax.annotation.Nullable
  public Map<String, InnerEnum> getSortFacetValuesBy() {
    return sortFacetValuesBy;
  }

  public void setSortFacetValuesBy(@javax.annotation.Nullable Map<String, InnerEnum> sortFacetValuesBy) {
    this.sortFacetValuesBy = sortFacetValuesBy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchSettingsFaceting searchSettingsFaceting = (SearchSettingsFaceting) o;
    return Objects.equals(this.maxValuesPerFacet, searchSettingsFaceting.maxValuesPerFacet) &&
        Objects.equals(this.sortFacetValuesBy, searchSettingsFaceting.sortFacetValuesBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxValuesPerFacet, sortFacetValuesBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchSettingsFaceting {\n");
    sb.append("    maxValuesPerFacet: ").append(toIndentedString(maxValuesPerFacet)).append("\n");
    sb.append("    sortFacetValuesBy: ").append(toIndentedString(sortFacetValuesBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("maxValuesPerFacet", "sortFacetValuesBy"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchSettingsFaceting
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchSettingsFaceting.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchSettingsFaceting is not found in the empty JSON string", SearchSettingsFaceting.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchSettingsFaceting.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchSettingsFaceting` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchSettingsFaceting.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchSettingsFaceting' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchSettingsFaceting> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchSettingsFaceting.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchSettingsFaceting>() {
           @Override
           public void write(JsonWriter out, SearchSettingsFaceting value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchSettingsFaceting read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchSettingsFaceting given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchSettingsFaceting
   * @throws IOException if the JSON string is invalid with respect to SearchSettingsFaceting
   */
  public static SearchSettingsFaceting fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchSettingsFaceting.class);
  }

  /**
   * Convert an instance of SearchSettingsFaceting to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

