/*
 * Hanzo Cloud — Unified API (V8 · Open Edition)
 * The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/_*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.
 *
 * The version of the OpenAPI document: 8.0.0
 * Contact: support@hanzo.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.hanzo.cloud.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.hanzo.cloud.JSON;

/**
 * SearchRuntimeTogglableFeatures
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SearchRuntimeTogglableFeatures {
  public static final String SERIALIZED_NAME_VECTOR_STORE = "vectorStore";
  @SerializedName(SERIALIZED_NAME_VECTOR_STORE)
  @javax.annotation.Nullable
  private Boolean vectorStore;

  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @SerializedName(SERIALIZED_NAME_METRICS)
  @javax.annotation.Nullable
  private Boolean metrics;

  public static final String SERIALIZED_NAME_LOGS_ROUTE = "logsRoute";
  @SerializedName(SERIALIZED_NAME_LOGS_ROUTE)
  @javax.annotation.Nullable
  private Boolean logsRoute;

  public static final String SERIALIZED_NAME_EDIT_DOCUMENTS_BY_FUNCTION = "editDocumentsByFunction";
  @SerializedName(SERIALIZED_NAME_EDIT_DOCUMENTS_BY_FUNCTION)
  @javax.annotation.Nullable
  private Boolean editDocumentsByFunction;

  public static final String SERIALIZED_NAME_CONTAINS_FILTER = "containsFilter";
  @SerializedName(SERIALIZED_NAME_CONTAINS_FILTER)
  @javax.annotation.Nullable
  private Boolean containsFilter;

  public static final String SERIALIZED_NAME_NETWORK = "network";
  @SerializedName(SERIALIZED_NAME_NETWORK)
  @javax.annotation.Nullable
  private Boolean network;

  public static final String SERIALIZED_NAME_CHAT_COMPLETIONS = "chatCompletions";
  @SerializedName(SERIALIZED_NAME_CHAT_COMPLETIONS)
  @javax.annotation.Nullable
  private Boolean chatCompletions;

  public static final String SERIALIZED_NAME_MULTI_MODAL = "multiModal";
  @SerializedName(SERIALIZED_NAME_MULTI_MODAL)
  @javax.annotation.Nullable
  private Boolean multiModal;

  public static final String SERIALIZED_NAME_EXPORT_PUFFIN_REPORTS = "exportPuffinReports";
  @SerializedName(SERIALIZED_NAME_EXPORT_PUFFIN_REPORTS)
  @javax.annotation.Nullable
  private Boolean exportPuffinReports;

  public static final String SERIALIZED_NAME_GET_TASK_DOCUMENTS_ROUTE = "getTaskDocumentsRoute";
  @SerializedName(SERIALIZED_NAME_GET_TASK_DOCUMENTS_ROUTE)
  @javax.annotation.Nullable
  private Boolean getTaskDocumentsRoute;

  public static final String SERIALIZED_NAME_COMPOSITE_EMBEDDERS = "compositeEmbedders";
  @SerializedName(SERIALIZED_NAME_COMPOSITE_EMBEDDERS)
  @javax.annotation.Nullable
  private Boolean compositeEmbedders;

  public SearchRuntimeTogglableFeatures() {
  }

  public SearchRuntimeTogglableFeatures vectorStore(@javax.annotation.Nullable Boolean vectorStore) {
    this.vectorStore = vectorStore;
    return this;
  }

  /**
   * Get vectorStore
   * @return vectorStore
   */
  @javax.annotation.Nullable
  public Boolean getVectorStore() {
    return vectorStore;
  }

  public void setVectorStore(@javax.annotation.Nullable Boolean vectorStore) {
    this.vectorStore = vectorStore;
  }


  public SearchRuntimeTogglableFeatures metrics(@javax.annotation.Nullable Boolean metrics) {
    this.metrics = metrics;
    return this;
  }

  /**
   * Get metrics
   * @return metrics
   */
  @javax.annotation.Nullable
  public Boolean getMetrics() {
    return metrics;
  }

  public void setMetrics(@javax.annotation.Nullable Boolean metrics) {
    this.metrics = metrics;
  }


  public SearchRuntimeTogglableFeatures logsRoute(@javax.annotation.Nullable Boolean logsRoute) {
    this.logsRoute = logsRoute;
    return this;
  }

  /**
   * Get logsRoute
   * @return logsRoute
   */
  @javax.annotation.Nullable
  public Boolean getLogsRoute() {
    return logsRoute;
  }

  public void setLogsRoute(@javax.annotation.Nullable Boolean logsRoute) {
    this.logsRoute = logsRoute;
  }


  public SearchRuntimeTogglableFeatures editDocumentsByFunction(@javax.annotation.Nullable Boolean editDocumentsByFunction) {
    this.editDocumentsByFunction = editDocumentsByFunction;
    return this;
  }

  /**
   * Get editDocumentsByFunction
   * @return editDocumentsByFunction
   */
  @javax.annotation.Nullable
  public Boolean getEditDocumentsByFunction() {
    return editDocumentsByFunction;
  }

  public void setEditDocumentsByFunction(@javax.annotation.Nullable Boolean editDocumentsByFunction) {
    this.editDocumentsByFunction = editDocumentsByFunction;
  }


  public SearchRuntimeTogglableFeatures containsFilter(@javax.annotation.Nullable Boolean containsFilter) {
    this.containsFilter = containsFilter;
    return this;
  }

  /**
   * Get containsFilter
   * @return containsFilter
   */
  @javax.annotation.Nullable
  public Boolean getContainsFilter() {
    return containsFilter;
  }

  public void setContainsFilter(@javax.annotation.Nullable Boolean containsFilter) {
    this.containsFilter = containsFilter;
  }


  public SearchRuntimeTogglableFeatures network(@javax.annotation.Nullable Boolean network) {
    this.network = network;
    return this;
  }

  /**
   * Get network
   * @return network
   */
  @javax.annotation.Nullable
  public Boolean getNetwork() {
    return network;
  }

  public void setNetwork(@javax.annotation.Nullable Boolean network) {
    this.network = network;
  }


  public SearchRuntimeTogglableFeatures chatCompletions(@javax.annotation.Nullable Boolean chatCompletions) {
    this.chatCompletions = chatCompletions;
    return this;
  }

  /**
   * Get chatCompletions
   * @return chatCompletions
   */
  @javax.annotation.Nullable
  public Boolean getChatCompletions() {
    return chatCompletions;
  }

  public void setChatCompletions(@javax.annotation.Nullable Boolean chatCompletions) {
    this.chatCompletions = chatCompletions;
  }


  public SearchRuntimeTogglableFeatures multiModal(@javax.annotation.Nullable Boolean multiModal) {
    this.multiModal = multiModal;
    return this;
  }

  /**
   * Get multiModal
   * @return multiModal
   */
  @javax.annotation.Nullable
  public Boolean getMultiModal() {
    return multiModal;
  }

  public void setMultiModal(@javax.annotation.Nullable Boolean multiModal) {
    this.multiModal = multiModal;
  }


  public SearchRuntimeTogglableFeatures exportPuffinReports(@javax.annotation.Nullable Boolean exportPuffinReports) {
    this.exportPuffinReports = exportPuffinReports;
    return this;
  }

  /**
   * Get exportPuffinReports
   * @return exportPuffinReports
   */
  @javax.annotation.Nullable
  public Boolean getExportPuffinReports() {
    return exportPuffinReports;
  }

  public void setExportPuffinReports(@javax.annotation.Nullable Boolean exportPuffinReports) {
    this.exportPuffinReports = exportPuffinReports;
  }


  public SearchRuntimeTogglableFeatures getTaskDocumentsRoute(@javax.annotation.Nullable Boolean getTaskDocumentsRoute) {
    this.getTaskDocumentsRoute = getTaskDocumentsRoute;
    return this;
  }

  /**
   * Get getTaskDocumentsRoute
   * @return getTaskDocumentsRoute
   */
  @javax.annotation.Nullable
  public Boolean getGetTaskDocumentsRoute() {
    return getTaskDocumentsRoute;
  }

  public void setGetTaskDocumentsRoute(@javax.annotation.Nullable Boolean getTaskDocumentsRoute) {
    this.getTaskDocumentsRoute = getTaskDocumentsRoute;
  }


  public SearchRuntimeTogglableFeatures compositeEmbedders(@javax.annotation.Nullable Boolean compositeEmbedders) {
    this.compositeEmbedders = compositeEmbedders;
    return this;
  }

  /**
   * Get compositeEmbedders
   * @return compositeEmbedders
   */
  @javax.annotation.Nullable
  public Boolean getCompositeEmbedders() {
    return compositeEmbedders;
  }

  public void setCompositeEmbedders(@javax.annotation.Nullable Boolean compositeEmbedders) {
    this.compositeEmbedders = compositeEmbedders;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchRuntimeTogglableFeatures searchRuntimeTogglableFeatures = (SearchRuntimeTogglableFeatures) o;
    return Objects.equals(this.vectorStore, searchRuntimeTogglableFeatures.vectorStore) &&
        Objects.equals(this.metrics, searchRuntimeTogglableFeatures.metrics) &&
        Objects.equals(this.logsRoute, searchRuntimeTogglableFeatures.logsRoute) &&
        Objects.equals(this.editDocumentsByFunction, searchRuntimeTogglableFeatures.editDocumentsByFunction) &&
        Objects.equals(this.containsFilter, searchRuntimeTogglableFeatures.containsFilter) &&
        Objects.equals(this.network, searchRuntimeTogglableFeatures.network) &&
        Objects.equals(this.chatCompletions, searchRuntimeTogglableFeatures.chatCompletions) &&
        Objects.equals(this.multiModal, searchRuntimeTogglableFeatures.multiModal) &&
        Objects.equals(this.exportPuffinReports, searchRuntimeTogglableFeatures.exportPuffinReports) &&
        Objects.equals(this.getTaskDocumentsRoute, searchRuntimeTogglableFeatures.getTaskDocumentsRoute) &&
        Objects.equals(this.compositeEmbedders, searchRuntimeTogglableFeatures.compositeEmbedders);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vectorStore, metrics, logsRoute, editDocumentsByFunction, containsFilter, network, chatCompletions, multiModal, exportPuffinReports, getTaskDocumentsRoute, compositeEmbedders);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchRuntimeTogglableFeatures {\n");
    sb.append("    vectorStore: ").append(toIndentedString(vectorStore)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    logsRoute: ").append(toIndentedString(logsRoute)).append("\n");
    sb.append("    editDocumentsByFunction: ").append(toIndentedString(editDocumentsByFunction)).append("\n");
    sb.append("    containsFilter: ").append(toIndentedString(containsFilter)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    chatCompletions: ").append(toIndentedString(chatCompletions)).append("\n");
    sb.append("    multiModal: ").append(toIndentedString(multiModal)).append("\n");
    sb.append("    exportPuffinReports: ").append(toIndentedString(exportPuffinReports)).append("\n");
    sb.append("    getTaskDocumentsRoute: ").append(toIndentedString(getTaskDocumentsRoute)).append("\n");
    sb.append("    compositeEmbedders: ").append(toIndentedString(compositeEmbedders)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("vectorStore", "metrics", "logsRoute", "editDocumentsByFunction", "containsFilter", "network", "chatCompletions", "multiModal", "exportPuffinReports", "getTaskDocumentsRoute", "compositeEmbedders"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SearchRuntimeTogglableFeatures
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SearchRuntimeTogglableFeatures.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SearchRuntimeTogglableFeatures is not found in the empty JSON string", SearchRuntimeTogglableFeatures.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SearchRuntimeTogglableFeatures.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SearchRuntimeTogglableFeatures` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SearchRuntimeTogglableFeatures.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SearchRuntimeTogglableFeatures' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SearchRuntimeTogglableFeatures> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SearchRuntimeTogglableFeatures.class));

       return (TypeAdapter<T>) new TypeAdapter<SearchRuntimeTogglableFeatures>() {
           @Override
           public void write(JsonWriter out, SearchRuntimeTogglableFeatures value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SearchRuntimeTogglableFeatures read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SearchRuntimeTogglableFeatures given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SearchRuntimeTogglableFeatures
   * @throws IOException if the JSON string is invalid with respect to SearchRuntimeTogglableFeatures
   */
  public static SearchRuntimeTogglableFeatures fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SearchRuntimeTogglableFeatures.class);
  }

  /**
   * Convert an instance of SearchRuntimeTogglableFeatures to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

